09_master_production_catalogue.ipynb

Cell 1:
Imports + setup

Cell 2:
Import/recreate get_season_productions()

Cell 3:
Investigate season discovery

Cell 4:
Build get_all_season_ids()

Cell 5:
Test season discovery

Cell 6:
Loop through seasons

Cell 7:
Build master dataframe

Cell 8:
Validation

Cell 9:
Export production_catalogue.csv

In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
import re
import time

In [2]:
def get_season_productions(season_id):
    """
    Extract all Broadway productions listed for a season.

    Parameters
    ----------
    season_id : int or str

    Returns
    -------
    pandas.DataFrame
        Columns:
        - production_id
        - title
        - url
        - season_id
    """

    url = f"https://www.ibdb.com/season/{season_id}"

    response = requests.get(url)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")

    rows = []

    for a in soup.find_all("a", href=True):
        href = a["href"]

        match = re.search(r"/broadway-production/.*-(\d+)$", href)

        if match:
            rows.append({
                "production_id": match.group(1),
                "title": a.get_text(strip=True),
                "url": "https://www.ibdb.com" + href,
                "season_id": season_id
            })

    df = (
        pd.DataFrame(rows)
        .drop_duplicates(subset="production_id")
        .reset_index(drop=True)
    )

    assert df["production_id"].is_unique
    assert df["production_id"].notna().all()

    return df

In [3]:
url = "https://www.ibdb.com/broadway-season"

response = requests.get(url)

print(response.status_code)
print(response.text[:500])

404




<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Live Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-20752142-5"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'UA-20752142-5');
</script>

<!-- Global site tag (gtag.js) - Google Analytics (GA4) -->
<script async src="https://www.googletagm

In [4]:
soup = BeautifulSoup(response.text, "html.parser")

links = [
    a.get("href")
    for a in soup.find_all("a")
]

links[:20]

season_links = [
    link for link in links
    if link and "season" in link.lower()
]

season_links[:20]

['/season/']

In [38]:
def check_season_exists(season_id, retries=3):
    url = f"https://www.ibdb.com/season/{season_id}"
    
    for attempt in range(retries):
        try:
            response = requests.get(url, timeout=10)
            soup = BeautifulSoup(response.text, "html.parser")
            
            title = soup.find("title")
            
            if title is None:
                return False
            
            if title.get_text(strip=True) == "Error":
                return False
            
            return True
        
        except requests.exceptions.RequestException:
            time.sleep(2)
    
    print(f"Failed after retries: {season_id}")
    return False

In [41]:
valid_season_ids = []

for season_id in range(1000, 1400):
    if check_season_exists(season_id):
        valid_season_ids.append(season_id)
        print("Found:", season_id)

    time.sleep(1)

Found: 1001
Found: 1002
Found: 1003
Found: 1004
Found: 1005
Found: 1006
Found: 1007
Found: 1008
Found: 1009
Found: 1010
Found: 1011
Found: 1012
Found: 1013
Found: 1014
Found: 1015
Found: 1016
Found: 1017
Found: 1018
Found: 1019
Found: 1020
Found: 1021
Found: 1022
Found: 1023
Found: 1024
Found: 1025
Found: 1026
Found: 1027
Found: 1028
Found: 1029
Found: 1030
Found: 1031
Found: 1032
Found: 1033
Found: 1034
Found: 1035
Found: 1036
Found: 1037
Found: 1038
Found: 1039
Found: 1040
Found: 1041
Found: 1042
Found: 1043
Found: 1044
Found: 1045
Found: 1046
Found: 1047
Found: 1048
Found: 1049
Found: 1050
Found: 1051
Found: 1052
Found: 1053
Found: 1054
Found: 1055
Found: 1056
Found: 1057
Found: 1058
Found: 1059
Found: 1060
Found: 1061
Found: 1062
Found: 1063
Found: 1064
Found: 1065
Found: 1066
Found: 1067
Found: 1068
Found: 1069
Found: 1070
Found: 1071
Found: 1072
Found: 1073
Found: 1074
Found: 1075
Found: 1076
Found: 1077
Found: 1078
Found: 1079
Found: 1080
Found: 1081
Found: 1082
Found: 1083
Found: 1084
Found: 1085
Found: 1086
Found: 1087
Found: 1088
Found: 1089
Found: 1090
Found: 1091
Found: 1092
Found: 1093
Found: 1094
Found: 1095
Found: 1096
Found: 1097
Found: 1098
Found: 1099
Found: 1100
Found: 1101
Found: 1102
Found: 1103
Found: 1104
Found: 1105
Found: 1106
Found: 1107
Found: 1108
Found: 1109
Found: 1110
Found: 1111
Found: 1112
Found: 1113
Found: 1114
Found: 1115
Found: 1116
Found: 1117
Found: 1118
Found: 1119
Found: 1120
Found: 1121
Found: 1122
Found: 1123
Found: 1124
Found: 1125
Found: 1126
Found: 1127
Found: 1128
Found: 1129
Found: 1130
Found: 1131
Found: 1132
Found: 1133
Found: 1134
Found: 1135
Found: 1136
Found: 1137
Found: 1138
Found: 1139
Found: 1140
Found: 1141
Found: 1142
Found: 1143
Found: 1144
Found: 1145
Found: 1146
Found: 1147
Found: 1148
Found: 1149
Found: 1150
Found: 1151
Found: 1152
Found: 1153
Found: 1154
Found: 1155
Found: 1156
Found: 1157
Found: 1158
Found: 1159
Found: 1160
Found: 1161
Found: 1162
Found: 1163
Found: 1164
Found: 1165
Found: 1166
Found: 1167
Found: 1168
Found: 1169
Found: 1170
Found: 1171
Found: 1172
Found: 1173
Found: 1174
Found: 1175
Found: 1176
Found: 1177
Found: 1178
Found: 1179
Found: 1180
Found: 1181
Found: 1182
Found: 1183
Found: 1184
Found: 1185
Found: 1186
Found: 1187
Found: 1188
Found: 1189
Found: 1190
Found: 1191
Found: 1192
Found: 1193
Found: 1194
Found: 1195
Found: 1196
Found: 1197
Found: 1198
Found: 1199
Found: 1200
Found: 1201
Found: 1202
Found: 1203
Found: 1204
Found: 1205
Found: 1206
Found: 1207
Found: 1208
Found: 1209
Found: 1210
Found: 1211
Found: 1212
Found: 1213
Found: 1214
Found: 1215
Found: 1216
Found: 1217
Found: 1218
Found: 1219
Found: 1220
Found: 1221
Found: 1222
Found: 1223
Found: 1224
Found: 1225
Found: 1226
Found: 1227
Found: 1228
Found: 1229
Found: 1230
Found: 1231
Found: 1232
Found: 1233
Found: 1234
Found: 1235
Found: 1236
Found: 1237
Found: 1238
Found: 1239
Found: 1240
Found: 1241
Found: 1242
Found: 1243
Found: 1244
Found: 1245
Found: 1246
Found: 1247
Found: 1248
Found: 1249
Found: 1267
Found: 1268
Found: 1270
Found: 1271
Found: 1272
Found: 1273
Found: 1274
Found: 1275
Found: 1276
Found: 1277
Found: 1278
Found: 1280
Found: 1281
Found: 1282
Found: 1283
Found: 1284
Found: 1285
Found: 1286
Found: 1287
Found: 1288
Found: 1289
Found: 1290
Found: 1291
Found: 1295
Found: 1296
Found: 1297
Found: 1298
Found: 1299

In [42]:
len(valid_season_ids)

277

In [43]:
valid_season_ids[:10], valid_season_ids[-10:]

([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
 [1287, 1288, 1289, 1290, 1291, 1295, 1296, 1297, 1298, 1299])

In [44]:
def get_season_label(season_id):
    url = f"https://www.ibdb.com/season/{season_id}"
    
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")
    
    text = soup.get_text(" ", strip=True)
    
    match = re.search(r"\d{4}-\d{4}", text)
    
    if match:
        return match.group()
    
    return None

In [51]:
import pandas as pd

pd.DataFrame({
    "season_id": valid_season_ids
}).to_csv(
    "valid_season_ids.csv",
    index=False
)

In [53]:
import time
import requests
from bs4 import BeautifulSoup
import re


def get_season_label(season_id, retries=5):
    url = f"https://www.ibdb.com/season/{season_id}"

    for attempt in range(retries):
        try:
            response = requests.get(
                url,
                timeout=15
            )

            soup = BeautifulSoup(response.text, "html.parser")

            text = soup.get_text(" ", strip=True)

            match = re.search(r"\d{4}-\d{4}", text)

            if match:
                return match.group()

            return None

        except requests.exceptions.RequestException as e:
            print(
                f"Retry {attempt+1}/{retries} failed for {season_id}"
            )
            time.sleep(3)

    print(f"Giving up on {season_id}")
    return None

    season_catalogue = []

for i, season_id in enumerate(valid_season_ids):

    print(f"{i+1}/{len(valid_season_ids)}: {season_id}")

    label = get_season_label(season_id)

    season_catalogue.append({
        "season_id": season_id,
        "season_label": label
    })

season_df = pd.DataFrame(season_catalogue)

season_df.head()

1/277: 1001
2/277: 1002
3/277: 1003
4/277: 1004
5/277: 1005
6/277: 1006
7/277: 1007
8/277: 1008
9/277: 1009
10/277: 1010
11/277: 1011
Retry 1/5 failed for 1011
12/277: 1012
13/277: 1013
14/277: 1014
15/277: 1015
16/277: 1016
17/277: 1017
18/277: 1018
19/277: 1019
20/277: 1020
21/277: 1021
22/277: 1022
23/277: 1023
24/277: 1024
25/277: 1025
26/277: 1026
27/277: 1027
28/277: 1028
29/277: 1029
30/277: 1030
31/277: 1031
32/277: 1032
33/277: 1033
34/277: 1034
35/277: 1035
36/277: 1036
37/277: 1037
38/277: 1038
39/277: 1039
40/277: 1040
41/277: 1041
42/277: 1042
43/277: 1043
44/277: 1044
45/277: 1045
46/277: 1046
47/277: 1047
48/277: 1048
49/277: 1049
50/277: 1050
51/277: 1051
52/277: 1052
53/277: 1053
54/277: 1054
55/277: 1055
56/277: 1056
57/277: 1057
58/277: 1058
59/277: 1059
60/277: 1060
61/277: 1061
62/277: 1062
63/277: 1063
64/277: 1064
65/277: 1065
66/277: 1066
67/277: 1067
68/277: 1068
69/277: 1069
70/277: 1070
71/277: 1071
72/277: 1072
73/277: 1073
74/277: 1074
75/277: 1075
76/277: 1076
77/277: 1077
78/277: 1078
79/277: 1079
80/277: 1080
81/277: 1081
82/277: 1082
83/277: 1083
84/277: 1084
85/277: 1085
86/277: 1086
87/277: 1087
88/277: 1088
89/277: 1089
90/277: 1090
91/277: 1091
92/277: 1092
93/277: 1093
94/277: 1094
95/277: 1095
96/277: 1096
97/277: 1097
98/277: 1098
99/277: 1099
100/277: 1100
101/277: 1101
102/277: 1102
103/277: 1103
104/277: 1104
105/277: 1105
106/277: 1106
107/277: 1107
108/277: 1108
109/277: 1109
110/277: 1110
111/277: 1111
112/277: 1112
113/277: 1113
114/277: 1114
115/277: 1115
116/277: 1116
117/277: 1117
118/277: 1118
119/277: 1119
120/277: 1120
121/277: 1121
122/277: 1122
123/277: 1123
124/277: 1124
125/277: 1125
126/277: 1126
127/277: 1127
128/277: 1128
129/277: 1129
130/277: 1130
131/277: 1131
132/277: 1132
133/277: 1133
134/277: 1134
135/277: 1135
136/277: 1136
137/277: 1137
138/277: 1138
139/277: 1139
140/277: 1140
141/277: 1141
142/277: 1142
143/277: 1143
144/277: 1144
145/277: 1145
146/277: 1146
147/277: 1147
148/277: 1148
149/277: 1149
150/277: 1150
151/277: 1151
152/277: 1152
153/277: 1153
154/277: 1154
155/277: 1155
156/277: 1156
157/277: 1157
158/277: 1158
159/277: 1159
160/277: 1160
161/277: 1161
162/277: 1162
163/277: 1163
164/277: 1164
165/277: 1165
166/277: 1166
167/277: 1167
168/277: 1168
169/277: 1169
170/277: 1170
171/277: 1171
172/277: 1172
173/277: 1173
174/277: 1174
175/277: 1175
176/277: 1176
177/277: 1177
178/277: 1178
179/277: 1179
180/277: 1180
181/277: 1181
182/277: 1182
183/277: 1183
184/277: 1184
185/277: 1185
186/277: 1186
187/277: 1187
188/277: 1188
189/277: 1189
190/277: 1190
191/277: 1191
192/277: 1192
193/277: 1193
194/277: 1194
195/277: 1195
196/277: 1196
197/277: 1197
198/277: 1198
199/277: 1199
200/277: 1200
201/277: 1201
202/277: 1202
203/277: 1203
204/277: 1204
205/277: 1205
206/277: 1206
207/277: 1207
208/277: 1208
209/277: 1209
210/277: 1210
211/277: 1211
212/277: 1212
213/277: 1213
214/277: 1214
215/277: 1215
216/277: 1216
217/277: 1217
218/277: 1218
219/277: 1219
220/277: 1220
Retry 1/5 failed for 1220
221/277: 1221
222/277: 1222
223/277: 1223
224/277: 1224
225/277: 1225
226/277: 1226
227/277: 1227
228/277: 1228
229/277: 1229
230/277: 1230
231/277: 1231
232/277: 1232
233/277: 1233
234/277: 1234
235/277: 1235
Retry 1/5 failed for 1235
236/277: 1236
237/277: 1237
238/277: 1238
Retry 1/5 failed for 1238
239/277: 1239
240/277: 1240
241/277: 1241
242/277: 1242
243/277: 1243
244/277: 1244
Retry 1/5 failed for 1244
245/277: 1245
246/277: 1246
247/277: 1247
248/277: 1248
249/277: 1249
250/277: 1267
251/277: 1268
252/277: 1270
253/277: 1271
254/277: 1272
255/277: 1273
256/277: 1274
257/277: 1275
Retry 1/5 failed for 1275
258/277: 1276
259/277: 1277
260/277: 1278
261/277: 1280
262/277: 1281
263/277: 1282
264/277: 1283
265/277: 1284
266/277: 1285
267/277: 1286
268/277: 1287
269/277: 1288
270/277: 1289
271/277: 1290
272/277: 1291
273/277: 1295
274/277: 1296
275/277: 1297
276/277: 1298
277/277: 1299

   season_id season_label
0       1001    1899-1900
1       1002    1900-1901
2       1003    1901-1902
3       1004    1902-1903
4       1005    1903-1904

In [58]:
season_catalogue = []

for i, season_id in enumerate(valid_season_ids):

    print(f"{i+1}/{len(valid_season_ids)}: {season_id}")

    label = get_season_label(season_id)

    season_catalogue.append({
        "season_id": season_id,
        "season_label": label
    })

season_df = pd.DataFrame(season_catalogue)

1/277: 1001
2/277: 1002
3/277: 1003
4/277: 1004
5/277: 1005
6/277: 1006
7/277: 1007
8/277: 1008
9/277: 1009
10/277: 1010
11/277: 1011
12/277: 1012
13/277: 1013
14/277: 1014
15/277: 1015
16/277: 1016
17/277: 1017
18/277: 1018
19/277: 1019
20/277: 1020
21/277: 1021
22/277: 1022
23/277: 1023
24/277: 1024
25/277: 1025
26/277: 1026
27/277: 1027
28/277: 1028
29/277: 1029
30/277: 1030
31/277: 1031
32/277: 1032
33/277: 1033
34/277: 1034
35/277: 1035
36/277: 1036
37/277: 1037
38/277: 1038
39/277: 1039
40/277: 1040
41/277: 1041
42/277: 1042
43/277: 1043
44/277: 1044
45/277: 1045
46/277: 1046
47/277: 1047
48/277: 1048
49/277: 1049
50/277: 1050
51/277: 1051
52/277: 1052
53/277: 1053
54/277: 1054
55/277: 1055
56/277: 1056
57/277: 1057
58/277: 1058
59/277: 1059
60/277: 1060
61/277: 1061
62/277: 1062
63/277: 1063
64/277: 1064
65/277: 1065
66/277: 1066
67/277: 1067
68/277: 1068
69/277: 1069
70/277: 1070
71/277: 1071
72/277: 1072
73/277: 1073
74/277: 1074
75/277: 1075
76/277: 1076
77/277: 1077
78/277: 1078
79/277: 1079
80/277: 1080
81/277: 1081
82/277: 1082
83/277: 1083
84/277: 1084
85/277: 1085
86/277: 1086
87/277: 1087
88/277: 1088
89/277: 1089
90/277: 1090
91/277: 1091
92/277: 1092
93/277: 1093
94/277: 1094
95/277: 1095
96/277: 1096
97/277: 1097
98/277: 1098
99/277: 1099
100/277: 1100
101/277: 1101
102/277: 1102
103/277: 1103
104/277: 1104
105/277: 1105
106/277: 1106
107/277: 1107
108/277: 1108
109/277: 1109
110/277: 1110
111/277: 1111
112/277: 1112
113/277: 1113
114/277: 1114
115/277: 1115
116/277: 1116
117/277: 1117
118/277: 1118
119/277: 1119
120/277: 1120
121/277: 1121
122/277: 1122
123/277: 1123
124/277: 1124
125/277: 1125
126/277: 1126
127/277: 1127
128/277: 1128
129/277: 1129
130/277: 1130
131/277: 1131
132/277: 1132
133/277: 1133
134/277: 1134
135/277: 1135
136/277: 1136
137/277: 1137
138/277: 1138
139/277: 1139
140/277: 1140
141/277: 1141
142/277: 1142
143/277: 1143
144/277: 1144
145/277: 1145
146/277: 1146
147/277: 1147
148/277: 1148
149/277: 1149
150/277: 1150
151/277: 1151
152/277: 1152
153/277: 1153
154/277: 1154
155/277: 1155
156/277: 1156
157/277: 1157
158/277: 1158
159/277: 1159
160/277: 1160
161/277: 1161
162/277: 1162
163/277: 1163
164/277: 1164
165/277: 1165
166/277: 1166
167/277: 1167
168/277: 1168
169/277: 1169
170/277: 1170
171/277: 1171
172/277: 1172
173/277: 1173
174/277: 1174
175/277: 1175
176/277: 1176
177/277: 1177
178/277: 1178
179/277: 1179
180/277: 1180
181/277: 1181
182/277: 1182
183/277: 1183
184/277: 1184
185/277: 1185
186/277: 1186
187/277: 1187
188/277: 1188
189/277: 1189
190/277: 1190
191/277: 1191
192/277: 1192
193/277: 1193
194/277: 1194
195/277: 1195
196/277: 1196
197/277: 1197
198/277: 1198
199/277: 1199
200/277: 1200
201/277: 1201
202/277: 1202
203/277: 1203
204/277: 1204
205/277: 1205
206/277: 1206
207/277: 1207
208/277: 1208
209/277: 1209
210/277: 1210
211/277: 1211
212/277: 1212
213/277: 1213
214/277: 1214
215/277: 1215
216/277: 1216
217/277: 1217
218/277: 1218
219/277: 1219
220/277: 1220
221/277: 1221
222/277: 1222
223/277: 1223
224/277: 1224
225/277: 1225
226/277: 1226
227/277: 1227
228/277: 1228
229/277: 1229
230/277: 1230
231/277: 1231
232/277: 1232
233/277: 1233
234/277: 1234
235/277: 1235
236/277: 1236
237/277: 1237
238/277: 1238
239/277: 1239
240/277: 1240
241/277: 1241
242/277: 1242
243/277: 1243
244/277: 1244
245/277: 1245
246/277: 1246
247/277: 1247
248/277: 1248
249/277: 1249
250/277: 1267
251/277: 1268
252/277: 1270
253/277: 1271
254/277: 1272
255/277: 1273
256/277: 1274
257/277: 1275
258/277: 1276
259/277: 1277
260/277: 1278
261/277: 1280
262/277: 1281
263/277: 1282
264/277: 1283
265/277: 1284
266/277: 1285
267/277: 1286
268/277: 1287
269/277: 1288
270/277: 1289
271/277: 1290
272/277: 1291
273/277: 1295
274/277: 1296
275/277: 1297
276/277: 1298
277/277: 1299

In [64]:
season_df.shape

(277, 2)

In [67]:
season_df.tail(20)

     season_id season_label
257       1276    2007-2008
258       1277    2008-2009
259       1278          NaN
260       1280          NaN
261       1281          NaN
262       1282          NaN
263       1283          NaN
264       1284          NaN
265       1285          NaN
266       1286          NaN
267       1287          NaN
268       1288    2018-2019
269       1289    2019-2020
270       1290    2020-2021
271       1291          NaN
272       1295          NaN
273       1296          NaN
274       1297          NaN
275       1298    2025-2026
276       1299    2026-2027

In [68]:
season_df["season_label"].isna().sum()

np.int64(130)

In [69]:
season_df[season_df["season_label"].isna()]

     season_id season_label
38        1039          NaN
39        1040          NaN
40        1041          NaN
41        1042          NaN
42        1043          NaN
..         ...          ...
267       1287          NaN
271       1291          NaN
272       1295          NaN
273       1296          NaN
274       1297          NaN

[130 rows x 2 columns]

In [75]:
season_catalogue = []
failed_seasons = []

for i, season_id in enumerate(valid_season_ids):

    print(f"{i+1}/{len(valid_season_ids)}: {season_id}")

    label = get_season_label(season_id)

    if label is None:
        failed_seasons.append(season_id)

    season_catalogue.append({
        "season_id": season_id,
        "season_label": label
    })

season_df = pd.DataFrame(season_catalogue)

print("\nFinished!")
print(f"Total seasons: {len(season_df)}")
print(f"Missing labels: {season_df['season_label'].isna().sum()}")
print(f"Failed season IDs: {failed_seasons}")

1/277: 1001
2/277: 1002
3/277: 1003
4/277: 1004
5/277: 1005
6/277: 1006
7/277: 1007
8/277: 1008
9/277: 1009
10/277: 1010
11/277: 1011
12/277: 1012
13/277: 1013
14/277: 1014
15/277: 1015
16/277: 1016
17/277: 1017
18/277: 1018
19/277: 1019
20/277: 1020
21/277: 1021
22/277: 1022
23/277: 1023
24/277: 1024
25/277: 1025
26/277: 1026
27/277: 1027
28/277: 1028
29/277: 1029
30/277: 1030
31/277: 1031
32/277: 1032
33/277: 1033
34/277: 1034
35/277: 1035
36/277: 1036
37/277: 1037
38/277: 1038
39/277: 1039
40/277: 1040
41/277: 1041
42/277: 1042
43/277: 1043
44/277: 1044
45/277: 1045
46/277: 1046
47/277: 1047
48/277: 1048
49/277: 1049
50/277: 1050
51/277: 1051
52/277: 1052
53/277: 1053
Retry 1/5 failed for 1053
54/277: 1054
55/277: 1055
56/277: 1056
57/277: 1057
58/277: 1058
59/277: 1059
60/277: 1060
61/277: 1061
62/277: 1062
63/277: 1063
64/277: 1064
65/277: 1065
66/277: 1066
67/277: 1067
68/277: 1068
69/277: 1069
70/277: 1070
71/277: 1071
72/277: 1072
73/277: 1073
74/277: 1074
75/277: 1075
76/277: 1076
77/277: 1077
78/277: 1078
79/277: 1079
80/277: 1080
81/277: 1081
82/277: 1082
83/277: 1083
84/277: 1084
85/277: 1085
86/277: 1086
87/277: 1087
88/277: 1088
89/277: 1089
90/277: 1090
Retry 1/5 failed for 1090
91/277: 1091
92/277: 1092
93/277: 1093
Retry 1/5 failed for 1093
94/277: 1094
Retry 1/5 failed for 1094
95/277: 1095
96/277: 1096
97/277: 1097
98/277: 1098
99/277: 1099
100/277: 1100
101/277: 1101
102/277: 1102
103/277: 1103
104/277: 1104
105/277: 1105
106/277: 1106
107/277: 1107
108/277: 1108
109/277: 1109
110/277: 1110
111/277: 1111
Retry 1/5 failed for 1111
112/277: 1112
113/277: 1113
114/277: 1114
115/277: 1115
116/277: 1116
117/277: 1117
118/277: 1118
119/277: 1119
120/277: 1120
121/277: 1121
122/277: 1122
123/277: 1123
124/277: 1124
125/277: 1125
126/277: 1126
127/277: 1127
128/277: 1128
129/277: 1129
130/277: 1130
131/277: 1131
132/277: 1132
133/277: 1133
134/277: 1134
135/277: 1135
136/277: 1136
137/277: 1137
138/277: 1138
139/277: 1139
140/277: 1140
141/277: 1141
142/277: 1142
143/277: 1143
144/277: 1144
145/277: 1145
146/277: 1146
147/277: 1147
148/277: 1148
149/277: 1149
150/277: 1150
151/277: 1151
152/277: 1152
153/277: 1153
154/277: 1154
155/277: 1155
156/277: 1156
157/277: 1157
158/277: 1158
159/277: 1159
160/277: 1160
161/277: 1161
162/277: 1162
163/277: 1163
164/277: 1164
165/277: 1165
166/277: 1166
167/277: 1167
168/277: 1168
169/277: 1169
170/277: 1170
Retry 1/5 failed for 1170
171/277: 1171
172/277: 1172
173/277: 1173
174/277: 1174
175/277: 1175
176/277: 1176
177/277: 1177
178/277: 1178
179/277: 1179
180/277: 1180
181/277: 1181
182/277: 1182
183/277: 1183
184/277: 1184
185/277: 1185
186/277: 1186
187/277: 1187
188/277: 1188
189/277: 1189
190/277: 1190
191/277: 1191
192/277: 1192
193/277: 1193
194/277: 1194
195/277: 1195
196/277: 1196
197/277: 1197
198/277: 1198
199/277: 1199
200/277: 1200
201/277: 1201
202/277: 1202
203/277: 1203
204/277: 1204
205/277: 1205
206/277: 1206
207/277: 1207
208/277: 1208
209/277: 1209
210/277: 1210
211/277: 1211
212/277: 1212
213/277: 1213
214/277: 1214
215/277: 1215
216/277: 1216
217/277: 1217
218/277: 1218
219/277: 1219
220/277: 1220
221/277: 1221
222/277: 1222
223/277: 1223
224/277: 1224
225/277: 1225
226/277: 1226
227/277: 1227
228/277: 1228
229/277: 1229
230/277: 1230
231/277: 1231
232/277: 1232
233/277: 1233
234/277: 1234
235/277: 1235
236/277: 1236
237/277: 1237
238/277: 1238
239/277: 1239
240/277: 1240
241/277: 1241
242/277: 1242
243/277: 1243
244/277: 1244
245/277: 1245
246/277: 1246
247/277: 1247
248/277: 1248
249/277: 1249
250/277: 1267
251/277: 1268
252/277: 1270
253/277: 1271
254/277: 1272
255/277: 1273
256/277: 1274
257/277: 1275
258/277: 1276
259/277: 1277
260/277: 1278
261/277: 1280
262/277: 1281
263/277: 1282
264/277: 1283
265/277: 1284
266/277: 1285
267/277: 1286
268/277: 1287
269/277: 1288
270/277: 1289
271/277: 1290
272/277: 1291
273/277: 1295
274/277: 1296
275/277: 1297
276/277: 1298
277/277: 1299

Finished!
Total seasons: 277
Missing labels: 79
Failed season IDs: [1039, 1040, 1041, 1042, 1043, 1047, 1048, 1049, 1050, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1238, 1239, 1240, 1244, 1245, 1246, 1247, 1248, 1270, 1271, 1272, 1273, 1277, 1278, 1280, 1281, 1282, 1286, 1287, 1288, 1289, 1296, 1297, 1298, 1299]

In [77]:
retry_catalogue = []

for season_id in failed_seasons:
    print(season_id)
    
    label = get_season_label(season_id)

    retry_catalogue.append({
        "season_id": season_id,
        "season_label": label
    })

retry_df = pd.DataFrame(retry_catalogue)

print("Still missing:")
print(retry_df["season_label"].isna().sum())

retry_df

1039
1040
1041
1042
1043
1047
1048
1049
1050
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1238
1239
1240
1244
1245
1246
1247
1248
1270
1271
1272
1273
1277
1278
1280
1281
1282
1286
1287
1288
1289
1296
Retry 1/5 failed for 1296
1297
1298
1299
Still missing:
7

    season_id season_label
0        1039    1937-1938
1        1040    1938-1939
2        1041    1939-1940
3        1042    1940-1941
4        1043    1941-1942
..        ...          ...
74       1289          NaN
75       1296    2023-2024
76       1297    2024-2025
77       1298    2025-2026
78       1299    2026-2027

[79 rows x 2 columns]

In [78]:
retry_df[retry_df["season_label"].isna()]

    season_id season_label
68       1280          NaN
69       1281          NaN
70       1282          NaN
71       1286          NaN
72       1287          NaN
73       1288          NaN
74       1289          NaN

In [79]:
season_df = season_df.merge(
    retry_df,
    on="season_id",
    how="left",
    suffixes=("", "_retry")
)

In [86]:
season_df["season_label"] = (
    season_df["season_label"]
    .fillna(season_df["season_label_retry"])
)

In [87]:
season_df = season_df.drop(columns="season_label_retry")

In [88]:
season_df[season_df["season_label"].isna()]

     season_id season_label
260       1280          NaN
261       1281          NaN
262       1282          NaN
266       1286          NaN
267       1287          NaN
268       1288          NaN
269       1289          NaN

In [91]:
season_df.to_csv(
    "season_catalogue.csv",
    index=False
)

In [92]:
season_df[season_df["season_label"].isna()]

     season_id season_label
260       1280          NaN
261       1281          NaN
262       1282          NaN
266       1286          NaN
267       1287          NaN
268       1288          NaN
269       1289          NaN

In [93]:
season_df[
    season_df["season_id"].between(1275, 1290)
]

     season_id season_label
256       1275    2006-2007
257       1276    2007-2008
258       1277    2008-2009
259       1278    2009-2010
260       1280          NaN
261       1281          NaN
262       1282          NaN
263       1283    2013-2014
264       1284    2014-2015
265       1285    2015-2016
266       1286          NaN
267       1287          NaN
268       1288          NaN
269       1289          NaN
270       1290    2020-2021

In [94]:
season_overrides = pd.DataFrame({
    "season_id": [
        1280,
        1281,
        1282,
        1286,
        1287,
        1288,
        1289
    ],
    "season_label": [
        "2010-2011",
        "2011-2012",
        "2012-2013",
        "2016-2017",
        "2017-2018",
        "2018-2019",
        "2019-2020"
    ]
})

In [97]:
season_df = season_df.merge(
    season_overrides,
    on="season_id",
    how="left",
    suffixes=("", "_override")
)

season_df["season_label"] = (
    season_df["season_label"]
    .fillna(season_df["season_label_override"])
)

season_df = season_df.drop(columns="season_label_override")

In [98]:
season_df["season_label"].isna().sum()

np.int64(0)

In [106]:
season_df.to_csv(
    "season_catalogue.csv",
    index=False
)

In [103]:
season_df["start_year"] = (
    season_df["season_label"]
    .str.extract(r"(\d{4})")
    .astype(int)
)

In [105]:
season_df.tail()

     season_id season_label  start_year
272       1295    2022-2023        2022
273       1296    2023-2024        2023
274       1297    2024-2025        2024
275       1298    2025-2026        2025
276       1299    2026-2027        2026

In [107]:
season_df["season_label"].duplicated().sum()

np.int64(0)